In [ ]:
import numpy as np

Задача 1

In [ ]:
matrixA = np.array([[1, 2, 1], [-2, 1, 1]])
matrixB = np.array([[3, 1], [-1, 0], [2, 4]])
matrixC = np.array([[-2, 2], [1, -1], [1, 2]])
print ("Матрица A = :\n", matrixA)
print ("Матрица B = :\n", matrixB)
print ("Матрица C = :\n", matrixC)

Матрица A = :
 [[ 1  2  1]
 [-2  1  1]]
Матрица B = :
 [[ 3  1]
 [-1  0]
 [ 2  4]]
Матрица C = :
 [[-2  2]
 [ 1 -1]
 [ 1  2]]


In [ ]:
matrixA_t = matrixA.transpose()

In [ ]:
print('Результат: A + 2 * B')
print(matrixA_t + 2 * matrixB)
print('Результат: B + 2 * C')
print(matrixB + 2 * matrixC)

Результат: A + 2 * B
[[7 0]
 [0 1]
 [5 9]]
Результат: B + 2 * C
[[-1  5]
 [ 1 -2]
 [ 4  8]]


Задача 2

In [ ]:
matrix = np.fromfunction(lambda i, j : np.int32(i % 2 == j % 2),(8,8))
print(matrix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
